# Generated by Django 3.1.3 on 2020-11-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightpage', '0002_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidebar',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
